name: mlp-cw4
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit=11.3 # or omit if CPU/MPS only
  - pip
  - pip:
      - timm
      - diffusers
      - transformers
      - opencv-python
      - pandas
      - tqdm
      - matplotlib
