name: mlp-cw4
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit=11.3 # Remove or adjust this if on CPU/MPS
  - pillow # For PIL (image processing)
  - pip # Ensure pip is available
  - pip:
      - kaggle
      - peft
      - timm
      - diffusers[torch]>=0.14 # Ensure diffusers installs with torch compatibility
      - transformers>=4.25
      - opencv-python
      - numpy
      - pandas
      - tqdm
      - matplotlib
      - accelerate>=0.16 # Required for LoRA fine-tuning
      - safetensors # Faster & safer model checkpoint format
      - pyyaml # Commonly needed for config files
